### PR TITLE
Updates for 0.4.0 release

### PR DESCRIPTION
**Pull request by teeparham**
* Drop support for ruby 1.8.7
* Support ruby 2.2
* Simplify version handling
* Add license file

### CODE REVIEW

**Comment by ebenoist** [comment]
Is there anyway I can help get this 4.0 release in?

**Comment by guizmaii** [comment]
@ebenoist Yes you can. 

I forked the project (https://github.com/oegr/rgeo) to continue the work. If you want to become a maintainer, ask me ;)

**Comment by ebenoist** [comment]
@guizmaii I'd be happy to help. @teeparham @dazuma any thoughts on just handing this repo over instead of forcing a fork?

**Comment by teeparham** [comment]
How about we all work together here on this project? 

If there is an issue that affects you, submit a pull request.

**Comment by guizmaii** [comment]
@ebenoist 
I prefer to work here too but there're PRs and issues that have no answers at all.

If you have some knowlegde about the use of this gem. 
Write some docs with examples could be great ! Because the begin with this gem, even this @dazuma posts and the "Spatial_Programming_With_RGeo.md" are really painfull !

@teeparham 
IMO, just ask for PRs isn't enought. 
Lots of people doesn't have the time/knowlegde to undestand your code and correct it. 
But they surely help you to find bugs and correct bugs, with the little time/knowlegde they have.
And more they'll see that they can help, they will helped.

**Comment by eddietejeda** [comment]
I am not in favor of a fork and would prefer working together.

@teeparham providing a timeline for the 0.4.0 release would be helpful in alleviating concerns about the project. thoughts?

**Comment by teeparham** [comment]
@guizmaii feel free to fork it & fix away. I'd love it if you made a better version of rgeo.

Please note, it's not "my code". Daniel Azuma wrote this library & he no longer works on it. So it's "our code" now. I don't understand how much of this library works any better than you or anyone else does, most likely. (Thanks to Daniel, there have been over 1.1 million gem downloads of rgeo!)

@eddietejeda Good idea - I'll get a 0.4.0 release out by the end of the week.

:rainbow:

**Comment by dazuma** [comment]
Hello everyone,

As Tee mentioned, I unfortunately don't have bandwidth to maintain this gem actively, as I'm no longer using Ruby or doing geospatial work in my day job. I've handed the keys to Tee, and he is free to hand them to anyone he feels is interested/qualified to take up development.

@guizmail you are of course free to fork it, but if you are passionate about making rgeo better and would like to step up to maintain it (deal with pull requests, do releases, and provide leadership in the direction of the project), I'd love to have you on board and take ownership of this main repository, and I'm sure Tee would agree.

I'm still around and can try to answer questions about the internals as needed.

There are a number of things that ought to be done on it—foremost in my mind being a better error handling than just returning nil, as I'm sure many of us agree.

Daniel

**Pull request merged**
