### PR TITLE
Minor comestic tweaks to CI

### PR DESCRIPTION
**Pull request by mlarraz**
### Summary

* Better labels for tasks
* Use strings for Ruby versions to prevent rounding (3.0 -> 3, which would match 3.1)

### CODE REVIEW

**Comment by BuonOmo** [comment]
Great idea ! Would you have an idea to avoid the ❌ if mandatory checks passed as well ?

image

**Comment by mlarraz** [comment]
Before and after:
image image

It's not an issue yet because `3.0` is the only release of `3.x` so far, but once `3.1` comes out `3` will resolve to that instead.

**Comment by mlarraz** [comment]
> Great idea ! Would you have an idea to avoid the ❌ if mandatory checks passed as well ?

Unfortunately this is a UI issue I haven't found a good workaround for. The overall workflow itself still has a a success status, but this isn't clearly visible:
image

For now you could make certain checks required in the repo settings, to more clearly represent what is expected to pass.

**Comment by BuonOmo** [comment]
Oh i see, the issue is only here when there is a `.0` version, nice catch 🙂

**Comment by BuonOmo** [comment]
> For now you could make certain checks required in the repo settings, to more clearly represent what is expected to pass.

@keithdoggett I'll do so after we merge this PR

**Review by keithdoggett — APPROVED** [review]

**Comment by keithdoggett** [comment]
Thanks again @mlarraz!

It's definitely annoying that the :x: shows up on builds that pass, especially since travis supported that functionality. I've seen some issues open for it in GitHub, so hopefully, it gets fixed soon.

**Review by BuonOmo — APPROVED** [review]
LGTM!

**Pull request merged**
