### PR TITLE
V3 Docs

### PR DESCRIPTION
**Pull request by keithdoggett**
### Summary

* Add `NEWS.md` with discussion of the changes.
* Add Upgrading to RGeo Version 3.0 checklist.
* Update README

### CODE REVIEW

**Review by BuonOmo — APPROVED** [review]
LGTM!

The validity part makes me think that we should finish handling all the cases of methods that return null rather than raising before having the final release.

Thinking for instance at https://github.com/rgeo/rgeo/blob/0fb78f64c55a936116d1d3c86a953dc03494c5e8/lib/rgeo/geos/ffi_factory.rb#L431 which really should not be a safe access, since `Feature.cast` should not return nil.

Same for the capi counter parts:

- https://github.com/rgeo/rgeo/blob/ec23154b99b1dd2b7900a3c2e5073c138c56acbe/ext/geos_c_impl/factory.c#L865-L867
- https://github.com/rgeo/rgeo/blob/ec23154b99b1dd2b7900a3c2e5073c138c56acbe/ext/geos_c_impl/factory.c#L834-L835

**Comment by keithdoggett** [comment]
> The validity part makes me think that we should finish handling all the cases of methods that return null rather than raising before having the final release.

Yes, I agree. Do we just have to change these wrapper functions and instead of returning `NULL` raise a `GeosError`? Or do we have to do it on a method by method basis?

**Comment by BuonOmo** [comment]
@keithdoggett I'd go for the wrapper. For the capi implementation, it is already raising if not null neither a geos geometry, hence we already have the correct implementation if we remove the null condition. For ffi, I'd say we can go the same way.

**Comment by keithdoggett** [comment]
@BuonOmo sounds good. I can get a PR up for that soon.

**Pull request merged**
