### PR TITLE
Passing tests on jruby

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Some changes I made while I was trying to run the tests in JRuby.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I've cherry-pick some commits from #75, which is a better solution than my first approach. So this should also fix #60 and #73

**Comment by tneems** [comment]
:+1:

**Comment by teeparham** [comment]
Thanks for removing the ActiveRecord-related code in b0363cb . I have no idea what that is for, and it certainly does not belong in this gem.

I'll bump the version and release a new gem later today. This might call for a 1.0 release so people can more easily understand changes via SemVer.

Big thanks to @nextdayflight and @deivid-rodriguez !!! :trophy:

**Comment by deivid-rodriguez** [comment]
Thanks @teeparham !

**Pull request merged**
