### PR TITLE
Add geos capi buffer_with_style() support

### PR DESCRIPTION
**Pull request by ynelin**

### CODE REVIEW

**Comment by teeparham** [comment]
Thank you. Would you mind adding a test for this method?

**Comment by ynelin** [comment]
Yes, I think I will do this.

ср, 2 сент. 2015 г. в 18:30, Tee Parham <notifications@github.com>:

**Comment by ynelin** [comment]
Tests was added

**Comment by teeparham** [comment]
Thanks! :metal:

**Comment by teeparham** [comment]
What happened? The branch changed since I reviewed it. I reset master & reverted this merge.

I would like to merge only these 3 commits:
a7a7853
23faf57
1b16e36

@ynelin Can you open a new PR with only those 3 commits?

**Comment by ynelin** [comment]
Yeah, i will open new PR.

**Comment by ynelin** [comment]
New PR https://github.com/rgeo/rgeo/pull/108

**Pull request merged**
