### PR TITLE
Remove duplicate points when casting rings+lines

### PR DESCRIPTION
**Pull request by sosso**
I ran into a similar issue like #113, so I made this fix.  If you'd like it behind a config parameter or other changes, feel free to let me know.

Here's a polygon that chokes RGeo:  `'MULTIPOLYGON(((-122.10033416748 37.6906110800046,-122.10033416748 37.6906110800046,-122.075443267822 37.6911544368997,-122.075443267822 37.6911544368997,-122.057418823242 37.6933278246668,-122.057418823242 37.6933278246668,-122.045230865479 37.6956369793712,-122.045230865479 37.6956369793712,-122.046947479248 37.6899334219492,-122.033815383911 37.6705735585369,-122.015447616577 37.675329080766,-122.034072875977 37.7018849197626,-122.034072875977 37.7018849197626,-122.00626373291 37.7126153927168,-122.045917510986 37.7423479509276,-122.045917510986 37.7423479509276,-122.111663818359 37.7352888797979,-122.111663818359 37.7352888797979,-122.120418548584 37.7071816741417,-122.120418548584 37.7071816741417,-122.107887268066 37.6997117828282,-122.107887268066 37.6997117828282,-122.10033416748 37.6906110800046)))'`

### CODE REVIEW

**Comment by teeparham** [comment]
Thank you. This seems reasonable. Can you add a test with the polygon you listed? (`types_test.rb` seems like a good place for it)

**Comment by sosso** [comment]
Sure! The only thing is that it could be considered unexpected behavior,
given that it's altering the data it's parsing. Is just altering the data
in this manner in the spirit of the project? Or should it throw a warning
or error, be configurable, etc? I do think it's pretty harmless, but I
would personally like to know if my shape data had duplicate points, as
that problem chokes more GIS tools than just RGeo, and this fix would mask
that.

**Comment by teeparham** [comment]
Good point - perhaps `#cast` is not the right place to do this. The `#cast` method is doing too much as it is. Perhaps we need a `#clean` method on `Polygon`.

**Comment by sosso** [comment]
Perhaps, but that wouldn't cover this case. I suppose we could put it on
the factory, which the ActiveRecord adapter supports on a per-column basis?
Something similar to lenient multipolygon assertions.

**Comment by Ume1931** [comment]
When this commit will be merged to master?

**Comment by BuonOmo** [comment]
@sosso Thanks for the PR!

I cannot reproduce the issue with both ruby and capi factories with the current version of rgeo, hence I'll close the pull request, if one still encounters a related problem, please open a new issue

**Pull request closed without merging**
