### PR TITLE
add_check_validation_methods

### PR DESCRIPTION
**Pull request by ynelin**
Add mapping for 2 methods from geos:
- GEOSisValid_r => is_valid?
- GEOSisValidReason_r => is_valid_reason

### CODE REVIEW

**Comment by teeparham** [comment]
Thank you for this PR! Sorry it took so long for me to review it.

I see you used the method names from GEOS for consistency. I think we should rename the methods:

#### `valid?` instead of `is_valid?`

`valid?` is simpler & follows best practices for naming predicate methods (methods that return a boolean).

#### `invalid_reason` instead of `valid_reason`

This method returns the reason the polygon is invalid, so let's call it that. 

If it's valid, I assume the reason is nil. Can you add a test for that case?

**Comment by ynelin** [comment]
Rename methods
When the polygon is valid it returns "Valid Geometry", I added test for this.

**Comment by teeparham** [comment]
Something went wrong with the rebase, I think?

**Comment by ynelin** [comment]
Yep. I fixed that

**Pull request merged**
