### PR TITLE
Add #geometries and utilize #each for Enumerable

### PR DESCRIPTION
**Pull request by mylesboone**
### Summary

This implements https://github.com/rgeo/rgeo/issues/231 .

### Other Information

There's a very basic test as well. More just a test to ensure that classes that include `BasicGeometryCollectionMethods` respond to enumerable methods.

### CODE REVIEW

**Comment by mylesboone** [comment]
FWIW -- I personally think that it'd be a lot cleaner to not access Enumerable methods directly on `BasicGeometryCollectionMethods`, but instead through `#goemetries`. In the same vein, removing `#each`. But, probably not worth the deprecation, etc. Up to you if you want to keep `Enumerable`.

**Review by BuonOmo — APPROVED** [review]
Thank you very much for your first contribution, and welcome ! 

The implementation LGTM 🙂 

About extending `geometries` instead of `BasicGeometryCollectionMethods`, do you really see a risk ? I've seen the latter in some gems already.

@keithdoggett I'll let you review as well, and I think we could include that in a minor pretty soon (documentation is waiting for the next update to be on rubydoc.info !)

**Comment by mylesboone** [comment]
@BuonOmo I don't see a risk extending Enumerable in `BasicGeometryCollectionMethods`. I more just mean that we could take advantage of the fact that `geometries` is already an enumerable `Array` and for me, it would be more intuitive to call `my_geometry_collection.geometries.each{...}` over `my_geometry_collection.each{...}`, but I don't think there's any harm or risk in extending Enumerable in `BasicGeometryCollectionMethods`.

**Comment by BuonOmo** [comment]
@mylesboone fine, in that case I'd say we keep both for developers lazyness. @keithdoggett any opinion ?

**Review by keithdoggett — APPROVED** [review]

**Comment by keithdoggett** [comment]
@BuonOmo yeah let's just keep both. I don't see any reason to deprecate `each` right now.

@mylesboone looks good thanks for the PR!

**Comment by mylesboone** [comment]
@keithdoggett not sure what you're wanting in the History.md -- looks like that documents release changes. I assume you'll want other changes before a minor version change?

**Comment by keithdoggett** [comment]
@mylesboone sorry about the confusion. Usually there's a "HEAD" section with pending changes on master. I'll just merge and add that manually.

**Pull request merged**
