### PR TITLE
Update CAPI wrappers to ditch deprecated Data_Wrap_Struct

### PR DESCRIPTION
**Pull request by teckwan**
### Summary

Addresses https://github.com/rgeo/rgeo/issues/273, replacing `Data_Wrap_Struct` with its typed counterpart.

### Other Information

This is my first contribution in RGeo, and since I'm unfamiliar with the code styles, the codebase, and coding extension libraries in general, please don't hesitate to be critical and address even minor changes or cosmetic ones.

### CODE REVIEW

**Comment by BuonOmo** [comment]
@keithdoggett FYI, Teck is a coworker at Klaxit, I've paired reviewed the code already, and there will be some slight cosmetic changes, apart from that LGTM. I'll let you review after that :)

**Review by BuonOmo — APPROVED** [review]
LGTM!

**Review by keithdoggett — APPROVED** [review]
@teckwan thanks so much for your help with this! LGTM I just have a few questions.

1) Should we add the ability to mark these as movable, like we did in the proj4 extension (https://github.com/rgeo/rgeo-proj4/blob/3b55631538b54fd64d7410dd0e2e10be0280235f/ext/proj4_c_impl/main.c#L103-L119)? I figure this would be a good time to do it.

2) Should this be merged into v3-dev instead? Do you have any thoughts around that @BuonOmo?

**Comment by BuonOmo** [comment]
@keithdoggett 

On (1.) I definitely agree, yet this could be part of another PR since tests will be tricky.

On (2.) the only issue would be for apps building around private parts of our c api, I think this can be part of a patch without any issue.

**Comment by keithdoggett** [comment]
Ok cool so this should be good to merge then and we can add support for marking in a different PR then.

**Comment by keithdoggett** [comment]
Thanks @teckwan!

**Pull request merged**
